#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1
PROG=/usr/bin/udpbd-server

udpbd_log () {
	logger -t udpbd-server "$1"
}

start_service() {
	if [ "$(uci get udpbd-server.server.enabled)" = "0" ]; then
		return 1
	fi

	devname="$(uci get udpbd-server.server.path)"
	if [ -z "$devname" ]; then
		udpbd_log "no device specified in udpbd-server.server.path, exiting"
		return 1
	fi

	procd_open_instance
	procd_set_param command $PROG "$devname"
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_close_instance
}

